version: '3.9'

services:

  my_django_server:
    build: backend
    container_name: my_django_server

    command: python3 manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/backend


    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis

    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_DATABASES=16


  celery:
    build: backend
    container_name: 'demo_app_celery'
    command: celery -A backend worker -l info -P gevent
    volumes:
      - .:/backend
    links:
      - redis
    depends_on:
      - my_django_server
      - redis